# Generated by Django 4.2.30 on 2026-08-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rd_flip_be', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flipbook',
            table='flipbooks',
        ),
        migrations.AlterModelTable(
            name='flipbookpage',
            table='flipbook_pages',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
