# Generated by Django 4.2.30 on 2026-08-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_flip_be', '0004_user_credit_expire_date_user_left_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expired_credit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
