# Generated by Django 4.2.30 on 2026-08-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_flip_be', '0005_user_expired_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipbookpage',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
