# Generated by Django 4.2.30 on 2026-08-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_flip_be', '0006_flipbookpage_image_url_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipbook',
            name='flip_id',
            field=models.CharField(db_index=True, default='ejfutrjels', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
