# Generated by Django 4.2.30 on 2026-09-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_flip_be', '0008_order_plan_userplan_paymenttransaction_order_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipbook',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
