# Generated by Django 4.2.30 on 2026-09-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_flip_be', '0009_flipbook_active_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipbook',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flipbook',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flipbook',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
