# Generated by Django 4.2.30 on 2026-09-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_flip_be', '0010_alter_flipbook_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipbook',
            name='flip_id',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
    ]
