# Generated by Django 4.2.30 on 2026-09-14 19:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_flip_be', '0011_alter_flipbook_flip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='List of text items describing this plan', size=None),
        ),
    ]
