# Generated by Django 4.2.30 on 2026-09-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rd_flip_be", "0013_setting"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "contact_us",
                "ordering": ["-created_at"],
            },
        ),
    ]
