# Generated by Django 4.2.30 on 2026-09-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_flip_be', '0016_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('audio_url', models.URLField(max_length=2048)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'songs',
                'ordering': ['category', 'name'],
            },
        ),
    ]
