# Generated by Django 4.2.30 on 2026-09-28 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rd_flip_be", "0020_song_playable_audio_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flipbook",
            name="song_id",
        ),
        migrations.AddField(
            model_name="flipbook",
            name="song",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flipbooks",
                to="rd_flip_be.song",
            ),
        ),
    ]
