# Generated by Django 4.2.30 on 2026-09-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd_flip_be', '0021_remove_flipbook_song_id_flipbook_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('studio', 'Studio')], default='studio', max_length=20),
        ),
    ]
